name: vault_chain
description: "A cypto project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  http: ^1.5.0
  intl: ^0.20.2
  fl_chart: ^1.1.0
  skeletonizer: ^2.1.0+1
  equatable: ^2.0.7
  hive_ce: ^2.12.0
  path_provider: ^2.1.5
  persistent_bottom_nav_bar_v2: ^6.1.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  json_serializable: ^6.11.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_logo.png
    - assets/icons/
    - assets/bitcoin.csv
    
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sfpro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/sfpro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/sfpro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/sfpro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sfpro/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/sfpro/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/sfpro/SF-Pro-Display-RegularItalic.otf
          style: italic